'''
This file contains the Song class that represents a song and handles the creation of the song file.
'''
import os

class Song:
    def __init__(self, name, duration, structure, style_description, lyrics):
        self.name = name
        self.duration = duration
        self.structure = structure
        self.style_description = style_description
        sonicpi = "# --"+name.upper()+"-- \n# Generated by mITy.John music's agency. \n\n" + lyrics
        self.lyrics = sonicpi

    def create_song_file(self):
        # Create the songs directory if it doesn't exist
        if not os.path.exists('songs'):
            os.makedirs('songs')
        # Create the subdirectory for the song
        # song_directory = os.path.join('songs', self.name)
        #if not os.path.exists(song_directory):
        #    os.makedirs(song_directory)
        # Create the song file
        song_file = os.path.join('songs', self.name + '.rb')
        with open(song_file, 'w') as f:
            f.write(self.lyrics)

